### PR TITLE
Add dynamic modules/package definition

### PR DESCRIPTION
**Pull request by tomgrv**
Hi.

I just share this custo I made with DRY in mind to integrate seamlessly with nWidart/laravel-modules package

Thanks for your review :)

### CODE REVIEW

**Review by scheibo — COMMENTED** [review]
Hey @tomgrv - thanks for this PR (with documentation)! I think I need more context on laravel-modules (which seems to be a PHP project? I guess I'm confused as to how it relates) to understand the use case better (how does the dynamic file get written, whether its location matters, etc)? The general idea of having `subPackages` point to a file that contains the sub packages LGTM, I just have some questions about the specifics :)

1) Regarding `XXX_foo.json` - the `XXX_` convention bit feels fragile to me - I think it would be more consistent with how this package currently handles nested subpackages if instead the `XXX` was included in the dynamic module declaration JSON itself (eg, `"XXX/sub-package-1": true`). Perhaps this could be coupled with the idea that the sub package paths in the dynamic module file are relative to the JSON file instead of `package.json` (eg, then you could just do `"subPackages": "XXX/statuses.json"` and `"sub-package-1": true,` would still be referencing `<root>/XXX/sub-package-1`. Maybe I'm missing something fundamental about laravel-modules though that would make your chosen design more desirable though?
2) Why `true` and `false` as opposed to simply eliding packages that shouldnt be included or (more obviously) simply using a array instead of an object?

The other minor nit is that the logging in `list` might be spammy given it runs on every command and some projects may have a number of modules (eg. https://github.com/pkmn/ps/blob/master/package.json#L41), though I'm not super concerned with this and its easy enough to remove if it becomes an issue :)

**Comment by tomgrv** [comment]
Hi @scheibo 

laravel-modules is indeed a way to add self contained modules to laravel : php+js
this package leaves a json file at project root specifying which module is active or not. 
This feature do not have any link with php or laravel at all, it's just a starting point for this PR

==> I think you caught the main idea of having a file pointing to subpackages :)

1. the naming convention is fragile, you're right. Your proposal looks good, but I'm afraid the statuses file needs to be in root folder. I brainstorm on this.
2. having true/false vs direct editing leaves space for live activation/deactivation or can be used to keep trace of available-but-not-used modules.

logging can be decreased you're right.

Thanks for your openness & support 🤝

**Comment by tomgrv** [comment]
Should be more robust -and flexible- now with object-type definition, using key as folder and value as statuses file name.

🍒 Cherry on the cake, multiple folders can be handled if needed, allowing to have 'modules' group , 'packages' group, etc ...

Thanks for your review :)

**Comment by scheibo** [comment]
Thanks! I've released this as v4.1.0!

**Pull request merged**
